site_name: Anno Modding Tools
site_url: https://anno-mods.github.io/vscode-anno

plugins:
  - search
  - macros

nav:
  - Home: index.md
  - Get Started: get-started.md
  - Setup: setup.md
  - Editing:
    - Navigation: editing/navigation.md
    - Auto Complete: editing/auto-complete.md
    - Issue Analysis: editing/analysis.md
    - Templates: editing/templates.md
  - Tools:
    - Deploy Mods: tools/deploy.md
    - Blender Import: tools/blender-import.md
    - Reskin Models: tools/reskin.md
  - Download:
    - Plugin: https://marketplace.visualstudio.com/items?itemName=JakobHarder.anno-modding-tools
    - Node Package: https://github.com/anno-mods/vscode-anno/releases/latest/

theme:
  name: material
  logo: images/logo.svg
  favicon: images/logo.png
  palette:
  # Palette toggle for automatic mode
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/link
      name: Switch to light mode

  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: light blue
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode

  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: light blue
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to system preference
  features:
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - header.autohide
    - navigation.footer
    - navigation.sections
    # - navigation.tabs
    # - toc.integrate

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.snippets:
      base_path: docs
      check_paths: true
      dedent_subsections: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys
  - tables
  - toc:
      permalink: true
      toc_depth: 2

extra:
  annotate:
    xml:  [.na, .s, .s2]
